---
- name: install docker [Ubuntu]
  shell:
    cmd: curl https://get.docker.com | sh
    creates: /usr/bin/docker
    warn: False # To prevent warning on using curl as a cmd

- name: install python-docker [Ubuntu]
  apt:
    name: python3-docker
    state: present
    autoclean: yes
